/**
 * Generated by scripts/generate-migration-manifest.ts. Do not edit by hand:
 * CI fails when this does not match `prisma/migrations`.
 *
 * Requirements: Deployment 3.8
 *
 * What this build expects the database to have applied. The startup guard
 * compares it against the ledger and refuses to serve when the database is
 * behind — see src/lib/migrations/pending.ts for why that window exists.
 */

export const COMMITTED_MIGRATIONS: readonly string[] = [
  '20260620233208_init',
  '20260621182618_add_pre_session_recipient',
  '20260824233723_add_notification_delivery',
  '20260914212427_add_materialised_at',
  '20260915111500_backfill_materialised_at',
  '20260916140000_add_scheduler_heartbeat',
  '20260916150000_add_scheduler_tick_record',
  '20260918000000_add_email_prompts_enabled',
  '20260926074240_add_response_finalised_at',
  '20260926120000_add_interaction_idempotency_key',
];
