/**
 * Generates the status block at the top of AI_CONTEXT.md.
 *
 * Requirements: Traceability 1.1; Deployment 2.2
 *
 * That header asserted, for a month, that "Integration hardening is on
 * `feat/integration-hardening`" — merged 2026-08-26 — that
 * `requirement-coverage` "has never executed" when it runs on every pull
 * request, and that "Task 26 is the only work remaining" across eleven specs
 * that came after it. Every session is instructed to read this file first, so
 * the first thing every session learned was wrong.
 *
 * Prose cannot be kept true by rule; this project has now proved that twice, in
 * this file and in AGENTS.md's citation count. So the facts that rot are
 * computed and the prose says only what stays true.
 *
 * **What is deliberately not in here:** the current branch, the head commit, the
 * date, the number of tests. Those change on commits that do not touch a spec,
 * so `--check` would fail on unrelated work and be switched off within a week.
 * Git already answers all four, and answers them correctly.
 *
 * What is in here changes only when a spec changes, so regenerating is part of
 * the same commit that made it stale.
 *
 * Usage:
 *   npx tsx scripts/generate-status.ts           rewrites the block
 *   npx tsx scripts/generate-status.ts --check    fails if it is out of date
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';

export const START = '<!-- generated:status:start -->';
export const END = '<!-- generated:status:end -->';

export interface SpecTally {
  name: string;
  done: number;
  total: number;
}

/** Counts ticked and unticked task boxes in one tasks.md. */
export function tallyTasks(markdown: string): { done: number; total: number } {
  const done = (markdown.match(/^\s*-\s\[x\]/gim) ?? []).length;
  const open = (markdown.match(/^\s*-\s\[ \]/gm) ?? []).length;
  return { done, total: done + open };
}

/** Reads every spec's tally, in a stable order. */
export function readSpecTallies(specsDir = '.kiro/specs'): SpecTally[] {
  return readdirSync(specsDir)
    .sort()
    .flatMap(name => {
      const path = `${specsDir}/${name}/tasks.md`;
      if (!existsSync(path)) return [];
      return [{ name, ...tallyTasks(readFileSync(path, 'utf8')) }];
    });
}

/**
 * The block itself.
 *
 * A spec with everything ticked is listed as complete rather than as a
 * fraction, because "141/141" invites the reader to do arithmetic to learn
 * nothing.
 */
export function buildStatusBlock(tallies: SpecTally[]): string {
  const done = tallies.reduce((sum, spec) => sum + spec.done, 0);
  const total = tallies.reduce((sum, spec) => sum + spec.total, 0);
  const openSpecs = tallies.filter(spec => spec.done < spec.total);

  const lines = [
    START,
    '',
    '<!-- Generated by scripts/generate-status.ts. Do not edit by hand:',
    '     CI fails if this block does not match the specs. -->',
    '',
    `**${done} of ${total} task boxes are ticked**, across ${tallies.length} specs.`,
    '',
  ];

  if (openSpecs.length === 0) {
    lines.push('Every spec is closed.');
  } else {
    lines.push('Specs with open boxes:', '');
    lines.push('| Spec | Open |', '|---|---|');
    for (const spec of openSpecs) {
      lines.push(`| \`${spec.name}\` | ${spec.total - spec.done} of ${spec.total} |`);
    }
    lines.push('');
    lines.push(
      '*An open box is not automatically work to do — several are blocked on',
      'something outside the code, and say so where they are written.*',
    );
  }

  lines.push('', END);
  return lines.join('\n');
}

/** Replaces the block between the markers. Throws if they are missing. */
export function replaceBlock(document: string, block: string): string {
  const start = document.indexOf(START);
  const end = document.indexOf(END);

  if (start === -1 || end === -1 || end < start) {
    throw new Error(`Markers ${START} / ${END} not found in order`);
  }

  return document.slice(0, start) + block + document.slice(end + END.length);
}

export function run(
  argv: string[],
  output: { out(m: string): void; err(m: string): void } = { out: console.log, err: console.error },
  path = 'AI_CONTEXT.md',
): number {
  const block = buildStatusBlock(readSpecTallies());
  const raw = readFileSync(path, 'utf8');
  const crlf = raw.includes('\r\n');
  const document = raw.replace(/\r\n/g, '\n');
  const updated = replaceBlock(document, block);

  if (argv.includes('--check')) {
    if (updated === document) {
      output.out(`${path}: status block is up to date.`);
      return 0;
    }
    output.err(
      `${path}: the status block does not match the specs.\n` +
        'Run: npx tsx scripts/generate-status.ts',
    );
    return 1;
  }

  writeFileSync(path, crlf ? updated.replace(/\n/g, '\r\n') : updated);
  output.out(`${path}: status block written.`);
  return 0;
}

if (process.argv[1]?.endsWith('generate-status.ts')) {
  process.exit(run(process.argv.slice(2)));
}
