/**
 * Writes the list of committed migrations into a module the runtime can read.
 *
 * Requirements: Deployment 3.8; Feeling Responsive NFR 1.1
 *
 *   npx tsx scripts/generate-migration-manifest.ts           rewrites it
 *   npx tsx scripts/generate-migration-manifest.ts --check   fails if stale
 *
 * The startup guard needs to know which migrations this build expects, and
 * it cannot read `prisma/migrations` to find out. Two reasons, both learned
 * the hard way:
 *
 * - Those files are not traced into the serverless bundle, so at runtime on
 *   Vercel the directory is not there to read.
 * - Reading it would mean `path.resolve(process.cwd(), …)`, and a named
 *   `process.cwd()` is precisely what made Turbopack trace the whole project
 *   into every function — 665 files per route against 292 — which was removed
 *   the day before this was written. Re-adding it to find the migrations
 *   would cost more than the guard is worth.
 *
 * So the list is generated, and CI fails when it drifts. The same shape as
 * the status block in AI_CONTEXT.md, for the same reason: a fact that rots is
 * computed, not written by hand.
 */

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import path from 'node:path';

const MIGRATIONS_DIR = 'prisma/migrations';
const MANIFEST = 'src/lib/migrations/manifest.ts';

/** Every migration directory, in the order they apply. */
export function readCommittedMigrations(dir: string = MIGRATIONS_DIR): string[] {
  return readdirSync(dir)
    .filter(entry => statSync(path.join(dir, entry)).isDirectory())
    .filter(entry => existsSync(path.join(dir, entry, 'migration.sql')))
    .sort();
}

/** The manifest's contents for a given list. */
export function buildManifest(migrations: readonly string[]): string {
  return `/**
 * Generated by scripts/generate-migration-manifest.ts. Do not edit by hand:
 * CI fails when this does not match \`prisma/migrations\`.
 *
 * Requirements: Deployment 3.8
 *
 * What this build expects the database to have applied. The startup guard
 * compares it against the ledger and refuses to serve when the database is
 * behind — see src/lib/migrations/pending.ts for why that window exists.
 */

export const COMMITTED_MIGRATIONS: readonly string[] = [
${migrations.map(name => `  '${name}',`).join('\n')}
];
`;
}

export function run(
  argv: string[] = [],
  output: { out(m: string): void; err(m: string): void } = { out: console.log, err: console.error },
  dir: string = MIGRATIONS_DIR,
  manifestPath: string = MANIFEST,
): number {
  const expected = buildManifest(readCommittedMigrations(dir));
  const current = existsSync(manifestPath) ? readFileSync(manifestPath, 'utf8') : '';

  // Compare ignoring line endings, which differ by platform and by editor
  const same = current.replace(/\r\n/g, '\n') === expected;

  if (argv.includes('--check')) {
    if (same) {
      output.out(`${manifestPath}: up to date.`);
      return 0;
    }
    output.err(
      `${manifestPath} does not match ${dir}.\n` +
        'Run: npx tsx scripts/generate-migration-manifest.ts',
    );
    return 1;
  }

  const crlf = current.includes('\r\n');
  writeFileSync(manifestPath, crlf ? expected.replace(/\n/g, '\r\n') : expected);
  output.out(`${manifestPath}: written.`);
  return 0;
}

if (process.argv[1]?.endsWith('generate-migration-manifest.ts')) {
  process.exit(run(process.argv.slice(2)));
}
